name: Linux

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      tagname: ${{ steps.tagname.outputs.tagname }}
    env:
      IMAGE_TAG: fagram:build

    steps:
      - name: Set TAGNAME
        id: tagname
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            TAGNAME="${{ github.event.inputs.tagname }}"
          else
            TAGNAME="${GITHUB_REF#refs/tags/}"
          fi
          echo "TAGNAME=$TAGNAME" >> $GITHUB_ENV
          echo "tagname=$TAGNAME" >> $GITHUB_OUTPUT

      - name: Clone.
        uses: actions/checkout@v4
        with:
          submodules: recursive
          ref: ${{ env.TAGNAME }}

      - name: Pull Docker IMG
        run: |
          docker pull ghcr.io/telegramdesktop/tdesktop/centos_env
          docker tag ghcr.io/telegramdesktop/tdesktop/centos_env $IMAGE_TAG

      - name: Configure & Build FAgram with CMake
        run: |
          docker run --rm \
          -u $(id -u) \
          -v $PWD:/usr/src/tdesktop \
          $IMAGE_TAG \
          /usr/src/tdesktop/Telegram/build/docker/centos_env/build.sh \
          -D CMAKE_CONFIGURATION_TYPES=Release \
          -D CMAKE_INSTALL_PREFIX="/usr" \
          -D TDESKTOP_API_ID=${{ secrets.API_ID_CONFIG }} \
          -D TDESKTOP_API_HASH=${{ secrets.API_HASH_CONFIG }}

      - name: Create Tar
        run: |
          cd out/install
          tar -czvf fagram-${{ env.TAGNAME }}.tar.gz usr
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: fagram-${{ env.TAGNAME }}
          path: out/install/fagram-${{ env.TAGNAME }}.tar.gz

  trigger-rpm:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Trigger repository dispatch event
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.BVPAT }}
          repository: burhancodes/fagram-rpm
          event-type: new-release